workflows:

  react-native-android:
    name: Build React Native Android APK
    environment:
      node: latest
      flutter: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npm run android:build
    artifacts:
      - android/app/build/outputs/**/*.apk
