workflows:
  version: 2
  react-native-build:
    name: Build React Native App
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android APK
        script: npm run android:build
    artifacts:
      - android/app/build/outputs/**/*.apk
